//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenesisEdit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenesisEdit.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CQlJTkNMVURFCVNZU1RFTS5TDQoJCVJTU0VUCVNZU1RFTUVORA0KUExBWVg6CQlSUy5MCTANClBMQVkxWDoJCVJTLlcJMQ0KUExBWTJYOgkJUlMuVwkxDQpQTEFZWToJCVJTLkwJMA0KUExBWTFZOgkJUlMuVwkxDQpQTEFZMlk6CQlSUy5XCTENClRFTVBTQ1JFRU46CVJTLkIJNDA5Ng0KVEVNUFNDUkVFTjI6CVJTLkIJNDA5Ng0KDQolR0VfVVNFUlZBUiUNCg0KRU5EVkFSUzoJUlMuQgkwDQoNClVTRVJJTklUOglNT1ZFLlcJIzAsUExBWTFYDQoJCU1PVkUuVwkjMCxQTEFZMVkNCgkJTU9WRS5XCSMwLFBMQVkyWA0KCQlNT1ZFLlcJIzAsUExBWTJZDQoNCgkJRE1BRFVNUAlNQVBHRlgsJUdFX05VTV9CR19DSEFSUyUqMzIsJDIwDQoJCU1PVkUuTAkjMCxEMA0KCQlDTVAuVwkjJUdF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CODE_TEMPLATE {
            get {
                return ResourceManager.GetString("CODE_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAACbSURBVDhPpZNdDYAwDAY3JOAAEmTgAA/IQAMykICGyeABB1gY+RpKxtYyFi5Z+nQX2I9t18EbhaWeaI7HTFOiumYC5H7vaHFIQgywzLxFkkAsM1rkEdBkRorcgZzMxBEKfJWZMGKdc75EDnHNJp9CCRUuCUqlwIFLX1AaYRncv/A1EsrgsQe5SCyDZBO1iCQD8RTiiCaDn8/ZmBOW91iiXP2MvQAAAABJRU5ErkJggg==.
        /// </summary>
        internal static string CONV_TEST {
            get {
                return ResourceManager.GetString("CONV_TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YTstLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCjsJCVJFR0lTVEVSIEVRVUFURVMKOy0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KWjgwUkVROgkJRVFVCSRBMTExMDAKWjgwUkVTOgkJRVFVCSRBMTEyMDAKWjgwUkFNOgkJRVFVCSRBMDAwMDAKCkI0OgkJRVFVCTE8PDQKQjMwOgkJRVFVCTE8PDMwCgpWRFBfREFUQToJRVFVCSRGRkMwMDAwMApWRFBfU1RBVFVTOglFUVUJJEZGQzAwMDA0ClZEUF9DT05UUk9MOglFUVUJJEZGQzAwMDA0CgpWUkFNVzoJCUVRVQklMDEqQjMwKyUwMDAwKkI0CkNSQU1XOgkJRVFVCSUxMSpCMzArJTAwMDAqQjQKVlNSQU1XOgkJRVFV [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SYSTEM_CODE {
            get {
                return ResourceManager.GetString("SYSTEM_CODE", resourceCulture);
            }
        }
    }
}
