//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenesisEdit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenesisEdit.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CODE_TEMPLATE {
            get {
                return ResourceManager.GetString("CODE_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WjgwUkVROgkJRVFVCSRBMTExMDAKWjgwUkVTOgkJRVFVCSRBMTEyMDAKWjgwUkFNOgkJRVFVCSRBMDAwMDAKCkI0OgkJRVFVCTE8PDQKQjMwOgkJRVFVCTE8PDMwCgpWRFBfREFUQToJRVFVCSRGRkMwMDAwMApWRFBfU1RBVFVTOglFUVUJJEZGQzAwMDA0ClZEUF9DT05UUk9MOglFUVUJJEZGQzAwMDA0CgpWUkFNVzoJCUVRVQklMDEqQjMwKyUwMDAwKkI0CkNSQU1XOgkJRVFVCSUxMSpCMzArJTAwMDAqQjQKVlNSQU1XOgkJRVFVCSUwMSpCMzArJTAwMDEqQjQKVlJBTVI6CQlFUVUJJTAwKkIzMCslMDAwMCpCNApDUkFNUjoJCUVRVQklMDAqQjMwKyUwMDEwKkI0ClZTUkFNUjoJCUVRVQklMDAqQjMwKyUwMDAxKkI0RE1BVlJBTToJRVFVCSUwMSpCMzArJTEwMDAqQjQKRE1BQ1JB [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SYSTEM_CODE {
            get {
                return ResourceManager.GetString("SYSTEM_CODE", resourceCulture);
            }
        }
    }
}
