using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace GenesisEdit.Forms
{
	public partial class HelpWindow : Form
	{
		private static readonly Dictionary<string, string> HELP = new Dictionary<string, string>()
		{
			{ "Genesis Edit Help", "V2VsY29tZSB0byB0aGUgR2VuZXNpcyBFZGl0IEhlbHAgUGFnZSEKClBsZWFzZSBwaWNrIGEgdG9waWMgZnJvbSB0aGUgbGlzdCBvbiB0aGUgbGVmdA==" },
			{ "Genesis Edit Help.Macros", "TWFjcm9zIGFyZSBzbmlwcGV0cyB0aGF0IHRoZSBHZW5lc2lzIEVkaXQgY29tcGlsZXIgY29udmVydHMgaW4gdG8gYXNzZW1ibHkgYmVmb3JlIHlvdXIgY29kZSBpcyBhc3NlbWJsZWQuIFRvIGxlYXJuIGFib3V0IGVhY2ggbWFjcm8sIGNsaWNrIG9uZSBmcm9tIHVuZGVyIHRoZSBtYWNyb3Mgc2VjdGlvbiBvbiB0aGUgbGVmdC4KCioqQWxsIGFyZ3VtZW50cyBNVVNUIGJlIHNlcGVyYXRlZCBieSBzcGFjZXMqKgpHb29kOiAlSUYgQTAgPT0gQTElCkJhZDogICVJRiBBMD09QTEl" },
			{ "Genesis Edit Help.Macros.%IF%", "U3ludGF4OgolSUYgPFZBTFVFPiA8Q09NUEFSSVNPTj4gPFZBTFVFPiUKPENPREU+ClsKJUVMU0UlCjxDT0RFPgpdCiVFTkRJRiUKCkNPTVBBUklTT04gY2FuIGJlIGFueSBvZiB0aGVzZTogPT0gIT0gPj0gPD0gPCA+ClZBTFVFIGNhbiBiZTogQSB2YXJpYWJsZSwgRDAtNywgQTAtNyAqQTAtNwpJZiBhbiBBIHJlZ2lzdGVyIGhhcyAqIGJlZm9yZSBpdCBpdCB3aWxsIGNvbXBhcmUgd2l0aCB0aGUgdmFsdWUgYXQgdGhlIGFkZHJlc3Mgb2YgdGhlIEEgcmVnaXN0ZXI=" },
			{ "Genesis Edit Help.Macros.%IFMODE%", "U3ludGF4OiAlSUZNT0RFIChTSUdORUR8VU5TSUdORUQpJQoKTWFrZXMgaWYgc3RhdGVtZW50cyBjb21waWxlIHRvIGVpdGhlciB1c2Ugc2lnbmVkIG9yIHVuc2lnbmVkIGNvbXBhcmlzb25zCgoqKlRoaXMgZG9lcyBub3QgZWZmZWN0IHRoZSBhc3NlbWJseSBpdCBvbmx5IHNldHMgYSBmbGFnISBDaGFuZ2luZyB0aGlzIGF0IHJ1bnRpbWUgd2lsbCBOT1QgZWZmZWN0IGNvbXBhcmlzb25zISBJdCBvbmx5IGVmZmVjdHMgdGhlIGNvbXBpbGVyISoq" },
			{ "Genesis Edit Help.Macros.%SPRITE%", "U3ludGF4OgolU1BSSVRFIDxOQU1FPiAoWHxZKSAoPXwrPXwtPXwqPXwvPSkgPFZBTFVFPiBbKEJ8V3xMKShTfFUpXSUKT1IKJVNQUklURSA8TkFNRT4gRElSIChMRUZUfFJJR0hUKSUKCk1vZGlmeSBzcHJpdGUgZGF0YS4KVkFMVUUgY2FuIGJlIGFueSB2YWxpZCB2YWx1ZSwgc2VlICJNYWNybyBWYWx1ZXMiIGZvciBpbmZvCkZvciB0aGUgWHxZIHN5bnRheCBvcHRpb24sIHRoZSBCLFcsTCB0cmFuc2xhdGVzIHRvIHRoZSBiaXQgd2lkdGggdXNlZCBpbiB0aGUgY2FsY3VsYXRpb24uIApCID0gOCBiaXQKVyA9IDE2IGJpdApMID0gMzIgYml0ClRoZSBuZXh0IGNoYXJhY3RlciwgUyBvciBVIGRldGVybWluZXMgaWYgdGhlIGNhbGN1bGF0aW9uIGlzIHNpZ25lZCBvciB1bnNpbmdlZCAoT25seSBlZmZlY3RzICo9IGFuZCAvPSBhcyBvZiByaWdodCBub3cpIAooSWYgbGFzdCB0d28gY2hhcnMgbm90IGdpdmVuIGl0IGRlZmF1bHRzIHRvIExTKQ==" },
			{ "Genesis Edit Help.Macro Values", "QSBtYWNybyB2YWx1ZSAoVXN1YWxseSByZXByZXNlbnRlZCBieSA8VkFMVUU+IGluIGEgbWFjcm8ncyBzeW50YXgpIGNhbiBiZSB0aGUgZm9sbG93aW5nOgoKQSB2YXJpYWJsZSBuYW1lICpXSVRIT1VUICUncyo6IE15X1ZhcgpBIHJlZ2lzdGVyOiBEKDAgdG8gNyksIFsqXUEoMC03KQoKKipBNyBpcyB0aGUgc3RhY2sgcG9pbnRlciwgZG9udCBtb2RpZnkgaXQhKio=" },
			{ "Genesis Edit Help.Syntax Notation", "VGhpbmdzIHdpbGwgYmUgbm90YXRlZCBpbiB0aGlzIEhlbHAgbWVudSBpbiBjZXJ0YWluIHdheXMuCgpJZiBzb21ldGhpbmcgaXMgaW5zaWRlIG9mIDw+J3MgaXQgaXMgYSBhcmd1bWVudCB0aGF0IGNhbiBiZSBhbnl0aGluZywgbGlrZSA8TkFNRT4gb3IgPFZBTFVFPgoKSWYgbXVsdGlwbGUgdmFsdWVzIGFyZSBpbiAoKSdzIHNlcGVyYXRlZCBieSB8J3MsIHlvdSBtdXN0IGVudGVyIE9ORSBvZiB0aGUgdmFsdWVzCkV4OiAoQXxCfEMpIC0+IHlvdSBtdXN0IHB1dCBBLCBCLCBvciBDIG9yIGl0IHdpbGwgYmUgaW52YWxpZApJZiB3aGF0IGlzIGluc2lkZSBvZiB0aGUgKCkncyBpcyAyIG51bWJlcnMgd2l0aCBhIC0gYmV0d2VlbiwgeW91IG1heSBlbnRlciBhbnkgbnVtYmVyIGluIHRoZSByYW5nZQpFeDogKDAtNykgbWVhbnMgeW91IGNhbiBlbnRlciBhbnkgbnVtYmVyIGZyb20gMCB0byA3LCBpbmNsdXNpdmUuIDUgaXMgdmFsaWQsIGJ1dCA4IGlzIE5PVAooKSBjYW4gYWxzbyBiZSB1c2VkIHRvIGdyb3VwIHRoaW5ncyEKRXg6ICgoQVtCXUN8WFlaKXwoMTIzfDRbNV02KSkKClRoaW5ncyBpbiBbXSdzIGFyZSBvcHRpb25hbCwgeW91IGRvbnQgaGF2ZSB0byBlbnRlciB0aGVzZSBidXQgc29tZXRpbWVzIHlvdSBtaWdodCBuZWVkIHRvCgpQdXRpbmcgaXQgYWxsIHRvZ2V0aGVyOgooKFsqXUEoMC03KSl8KERbMC03XSkpIC0+IFZhbGlkOiBBMCwgRDUsICpBMSBJbnZhbGlkOiBBOCwgKkE5LCAqLCBBLCA3LCAqRDAsIEQ=" }
		};

		public HelpWindow()
		{
			InitializeComponent();
		}

		private void TopicFinder_AfterSelect(object sender, TreeViewEventArgs e)
		{
			if (HELP.TryGetValue(TopicFinder.SelectedNode.FullPath, out string s))
			{
				HelpText.Text = Encoding.ASCII.GetString(Convert.FromBase64String(s)).Replace("\r", string.Empty).Replace("\n", "\r\n");
			}
		}
	}
}
