using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace GenesisEdit.Forms
{
	public partial class HelpWindow : Form
	{
		private static readonly Dictionary<string, string> HELP = new Dictionary<string, string>()
		{
			{ "Genesis Edit Help", "V2VsY29tZSB0byB0aGUgR2VuZXNpcyBFZGl0IEhlbHAgUGFnZSEKClBsZWFzZSBwaWNrIGEgdG9waWMgZnJvbSB0aGUgbGlzdCBvbiB0aGUgbGVmdA==" },
			{ "Genesis Edit Help.What is GenesisEdit?", "V2hhdCBpcyBHZW5lc2lzRWRpdD8KCkdlbmVzaXNFZGl0IGlzIGEgdG9vbCB0byBjb2RlIGdhbWVzIChpbiBhc3NlbWJseSkgZm9yIHRoZSBTZWdhIEdlbmVzaXMgKG9yIFNlZ2EgTWVnYURyaXZlKS4gSXQgaGFzIE1hY3JvcywgVmFyaWFibGVzLCBBdXRvbWF0aWMgc3ByaXRlIGFuZCBiYWNrZ3JvdW5kIGNvbXBpbGF0aW9uLCBhbmQgbW9yZS4gT3RoZXIgcGFnZXMgd2lsbCBnbyBpbnRvIG1vcmUgZGV0YWlsIG9uIGhvdyBHZW5lc2lzRWRpdCB3b3Jrcw==" },
			{ "Genesis Edit Help.What is GenesisEdit?.What is the Sega Genesis?", "" },
			{ "Genesis Edit Help.Macros", "TWFjcm9zIGFyZSBzbmlwcGV0cyB0aGF0IHRoZSBHZW5lc2lzIEVkaXQgY29tcGlsZXIgY29udmVydHMgaW4gdG8gYXNzZW1ibHkgYmVmb3JlIHlvdXIgY29kZSBpcyBhc3NlbWJsZWQuIFRvIGxlYXJuIGFib3V0IGVhY2ggbWFjcm8sIGNsaWNrIG9uZSBmcm9tIHVuZGVyIHRoZSBtYWNyb3Mgc2VjdGlvbiBvbiB0aGUgbGVmdC4KCioqQWxsIGFyZ3VtZW50cyBNVVNUIGJlIHNlcGVyYXRlZCBieSBzcGFjZXMqKgpHb29kOiAlSUYgQTAgPT0gQTElCkJhZDogICVJRiBBMD09QTEl" },
			{ "Genesis Edit Help.Macros.%IF%", "U3ludGF4OgolSUYgPFZBTFVFPiA8Q09NUEFSSVNPTj4gPFZBTFVFPiUKPENPREU+ClsKJUVMU0UlCjxDT0RFPgpdCiVFTkRJRiUKCkNPTVBBUklTT04gY2FuIGJlIGFueSBvZiB0aGVzZTogPT0gIT0gPj0gPD0gPCA+ClZBTFVFIGNhbiBiZTogQSB2YXJpYWJsZSwgRDAtNywgQTAtNyAqQTAtNwpJZiBhbiBBIHJlZ2lzdGVyIGhhcyAqIGJlZm9yZSBpdCBpdCB3aWxsIGNvbXBhcmUgd2l0aCB0aGUgdmFsdWUgYXQgdGhlIGFkZHJlc3Mgb2YgdGhlIEEgcmVnaXN0ZXI=" },
			{ "Genesis Edit Help.Macros.%SPRITE%", "U3ludGF4OgolU1BSSVRFIDxOQU1FPiAoWHxZKSAoPXwrPXwtPXwqPXwvPSkgPFZBTFVFPiBbKEJ8V3xMKShTfFUpXSUKT1IKJVNQUklURSA8TkFNRT4gRElSIChMRUZUfFJJR0hUKSUKCk1vZGlmeSBzcHJpdGUgZGF0YS4KVkFMVUUgY2FuIGJlIGFueSB2YWxpZCB2YWx1ZSwgc2VlICJNYWNybyBWYWx1ZXMiIGZvciBpbmZvCkZvciB0aGUgWHxZIHN5bnRheCBvcHRpb24sIHRoZSBCLFcsTCB0cmFuc2xhdGVzIHRvIHRoZSBiaXQgd2lkdGggdXNlZCBpbiB0aGUgY2FsY3VsYXRpb24uIApCID0gOCBiaXQKVyA9IDE2IGJpdApMID0gMzIgYml0ClRoZSBuZXh0IGNoYXJhY3RlciwgUyBvciBVIGRldGVybWluZXMgaWYgdGhlIGNhbGN1bGF0aW9uIGlzIHNpZ25lZCBvciB1bnNpbmdlZCAoT25seSBlZmZlY3RzICo9IGFuZCAvPSBhcyBvZiByaWdodCBub3cpIAooSWYgbGFzdCB0d28gY2hhcnMgbm90IGdpdmVuIGl0IGRlZmF1bHRzIHRvIExTKQ==" },
			{ "Genesis Edit Help.Macro Values", "QSBtYWNybyB2YWx1ZSAoVXN1YWxseSByZXByZXNlbnRlZCBieSA8VkFMVUU+IGluIGEgbWFjcm8ncyBzeW50YXgpIGNhbiBiZSB0aGUgZm9sbG93aW5nOgoKQSB2YXJpYWJsZSBuYW1lOiBNeV9WYXIKQSByZWdpc3RlcjogRCgwIHRvIDcpLCBbKl1BKDAtNykKCioqQTcgaXMgdGhlIHN0YWNrIHBvaW50ZXIsIGRvbnQgbW9kaWZ5IGl0ISoq" },
			{ "Genesis Edit Help.Syntax Notation", "VGhpbmdzIHdpbGwgYmUgbm90YXRlZCBpbiB0aGlzIEhlbHAgbWVudSBpbiBjZXJ0YWluIHdheXMuIEl0IGlzIHZlcnkgc2ltaWxhciB0byByZWdleGVzLCBzbyBpZiB5b3UgYXJlIHNlYXNvbmVkIGluIHJlZ2V4ZXMgaXQgd2lsbCBiZSBmYW1pbGlhciB0byB5b3UKCklmIHNvbWV0aGluZyBpcyBpbnNpZGUgb2YgPD4ncyBpdCBpcyBhIGFyZ3VtZW50IHRoYXQgY2FuIGJlIGFueXRoaW5nLCBsaWtlIDxOQU1FPiBvciA8VkFMVUU+CgpJZiBtdWx0aXBsZSB2YWx1ZXMgYXJlIGluICgpJ3Mgc2VwZXJhdGVkIGJ5IHwncywgeW91IG11c3QgZW50ZXIgT05FIG9mIHRoZSB2YWx1ZXMKRXg6IChBfEJ8QykgLT4geW91IG11c3QgcHV0IEEsIEIsIG9yIEMgb3IgaXQgd2lsbCBiZSBpbnZhbGlkCklmIHdoYXQgaXMgaW5zaWRlIG9mIHRoZSAoKSdzIGlzIDIgbnVtYmVycyB3aXRoIGEgLSBiZXR3ZWVuLCB5b3UgbWF5IGVudGVyIGFueSBudW1iZXIgaW4gdGhlIHJhbmdlCkV4OiAoMC03KSBtZWFucyB5b3UgY2FuIGVudGVyIGFueSBudW1iZXIgZnJvbSAwIHRvIDcsIGluY2x1c2l2ZS4gNSBpcyB2YWxpZCwgYnV0IDggaXMgTk9UCigpIGNhbiBhbHNvIGJlIHVzZWQgdG8gZ3JvdXAgdGhpbmdzIQpFeDogKChBW0JdQ3xYWVopfCgxMjN8NFs1XTYpKQoKVGhpbmdzIGluIFtdJ3MgYXJlIG9wdGlvbmFsIE9SIGl0IGluZGljYXRlcyB5b3UgaGF2ZSB0byBwdXQgaW4gb24gb2YgdGhlIGNoYXJhY3RlcnMgaW4uClNlZSBodHRwczovL3d3dy5yZXhlZ2cuY29tL3JlZ2V4LXF1aWNrc3RhcnQuaHRtbCNjbGFzc2VzIGZvciBkZXRhaWxzIG9uIHJhbmdlcwpFeDogW0FEXVswLTddID0gQSBPUiBELCB0aGVuIG51bWJlcnMgMCB0byA3CkVYOgoKUHV0aW5nIGl0IGFsbCB0b2dldGhlcjoKWyhbKl1BKURdWzAtN10gLT4gVmFsaWQ6IEEwLCBENSwgKkExIEludmFsaWQ6IEE4LCAqQTksICosIEEsIDcsICpEMCwgRCwgQS0sICpELQ==" },
			{ "Genesis Edit Help.Variables", "R2VuZXNpc0VkaXQgaGFzIHZhcmlhYmxlcywgd2hpY2ggY2FuIGFyZSByZXBsYWNlZCB3aXRoIHNvbWV0aGluZyBlbHNlIHdoZW4geW91ciBjb2RlIGlzIGNvbXBpbGVkLgoKWW91IHJlZmVyZW5jZSBhIHZhcmlhYmxlIGxpa2UgdGhpczoKJTxOQU1FPiUKRVg6IE1PVkUuVyAjJDEzMzcsJU15VmFyaWFibGUlCgpWYXJpYWJsZXMgY2FuIG9ubHkgY29udGFpbiBsZXR0ZXJzIChhLXogYW5kIEEtWiksIG51bWJlcnMgKDAtOSksIGFuZCB1bmRlcnNjb3JlcyAoXykKTk9URTogVmFyaWFibGVzIE1VU1Qgc3RhcnQgd2l0aCBhIGxldHRlciAoYS16IG9yIEEtWikgb3IgYW4gdW5kZXNjb3JlIChfKQpUbyBhZGQgYSB2YXJpYWJsZSwgb3BlbiB0aGUgIlZhcmlhYmxlcyIgdGFiIGluIEdlbmVzaXNFZGl0LgoKQnl0ZSwgV29yZCwgTG9uZz8gV2hhdD8KClRoZXNlIGFyZSBkaWZmZXJlbnQgc2l6ZXMgb2YgdmFyaWFibGVzLgpIZXJlIGFyZSByYW5nZXMgZm9yIGVhY2ggdHlwZToKQnl0ZSA9IDAgdG8gMjU1ICgtMTI4IHRvIDEyNykKV29yZCA9IDAgdG8gNjU1MzYgKC0zMjc2OCB0byAzMjc2NykKTG9uZyA9IDAgdG8gNDI5NDk2NzI5NiAoLTIxNDc0ODM2NDggdG8gMjE0NzQ4MzY0NykKU2l6ZXMgaW4gYml0czoKQnl0ZSA9IDggYml0cwpXb3JkID0gMTYgYml0cwpMb25nID0gMzIgYml0cwoK" }
		};

		public HelpWindow()
		{
			InitializeComponent();
		}

		private void TopicFinder_AfterSelect(object sender, TreeViewEventArgs e)
		{
			if (HELP.TryGetValue(TopicFinder.SelectedNode.FullPath, out string s))
			{
				HelpText.Text = Encoding.ASCII.GetString(Convert.FromBase64String(s)).Replace("\r", string.Empty).Replace("\n", "\r\n");
			}
		}
	}
}
